# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def install_pods
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PackList
  
  #pod 'GData'
  #pod 'Google-AdMob-Ads-SDK'
  #pod 'GoogleAnalytics-iOS-SDK',  '~> 3.0'
  #pod 'GoogleMobileAds'
  
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  
  #pod 'CocoaHTTPServer'
  #pod 'GTMHTTPFetcher'
  #pod 'SFHFKeychainUtils'
  
  pod 'CargoBay'


end

# PackListDev 開発版(com.azukid.AzPackList5) 常に先行公開
target 'PackListDev' do
    install_pods
end

# PackList 安定版(com.azukid.AzPackingS1)
target 'PackList' do
    install_pods
end


