# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def install_pods
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PackList
  
  #pod 'GData'
  #pod 'Google-AdMob-Ads-SDK'
  #pod 'GoogleAnalytics-iOS-SDK',  '~> 3.0'
  #pod 'GoogleMobileAds'
  
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  
  #pod 'CocoaHTTPServer'
  #pod 'GTMHTTPFetcher'
  #pod 'SFHFKeychainUtils'
  
  pod 'CargoBay'


end

# 安定版「少し新しいモチメモ」com.azukid.AzPackList5
target 'PackList' do
    install_pods
end

# 開発版「モチメモβ」com.azukid.c26b3b4dab9ca6 常に先行公開
target 'PackListBeta' do
    install_pods
end


#---
# OLD iPhone「モチメモ」com.azukid.AzPackingS1
target 'PackListTel' do
    install_pods
end

# OLD iPhone Free「モチメモ Free」com.azukid.AzPacking
target 'PackListTelFree' do
    install_pods
end

# OLD iPad「モチメモ for iPad」com.azukid.AzPackPadS1
target 'PackListPad' do
    install_pods
end

# OLD iPad Free「モチメモ Free for iPad」com.azukid.AzPackPadFree
target 'PackListPadFree' do
    install_pods
end


